# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

PS1='\[\033[01;32m\]\u \[\033[01;34m\]@\[\033[01;34m\]\h\[\033[01;36m\] \w \$\[\033[00m\] '

HISTFILESIZE='2000'

[[ -f /etc/profile.d/bash-completion.sh ]] && source /etc/profile.d/bash-completion.sh 

# Put your fun stuff here.
#alias ssh='ssh -Y'
alias webcam='LD_PRELOAD=/usr/lib/libv4l/v4l1compat.so  mplayer tv://1'
alias cam='LD_PRELOAD=/usr/lib/libv4l/v4l1compat.so  camorama'
alias sdiff='svn diff|view -'
alias tree='tree -A'
alias toff='synclient TouchpadOff=1'
alias ton='synclient TouchpadOff=0'
alias octave='octave -q'
alias bandeco='links -dump http://www.prefeitura.unicamp.br/servicos.php?servID=119 | head -n 23 | tail -n 14| sed "s/.\{0,35\}[ ]*//" | grep -v ^$ | sed -e "s/\//./g"'
alias vbox='modprobe vboxnetadp; sleep 5;modprobe vboxdrv;sleep 5;modprobe vboxnetflt;mount /media/vbox; VirtualBox'
alias vi='vi -p'
alias bi='vi'
# alias arduino='/home/paulo/tmp/arduino-0017/build/linux/work/arduino'

PATH="/usr/local/sbin:/usr/sbin:/sbin:${PATH}"
XSESSION="fluxbox"
PYTHONSTARTUP=$HOME/.pythonrc
export PYTHONSTARTUP

alias build='make clean && make && okular report.pdf'

export ECHANGELOG_USER="Paulo Machado <machado@las.ic.unicamp.br>"

