# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

# [[ -f /usr/share/git/completion/git-prompt.sh ]] && source /usr/share/git/completion/git-prompt.sh

# function _ps_line
# {
#    [[ $COLUMNS -lt 100 ]] && echo -e "\n-> "
# }

# PS1='\[\033[01;32m\]\[\033[0m\033[0;32m\]\[\033[01;33m\]\u\[\e[01;37m\]@\h\[\033[00m\] \[\033[01;34m\]\w\[\033[01;35m\] $(__git_ps1 [%s])$(_ps_line)$ \[\e[00m\]'

eval "$(starship init bash)"

HISTFILESIZE='5000'
HISTCONTROL='ignoreboth'

[[ -f /etc/bash_completion ]] && source /etc/bash_completion

# Put your fun stuff here.
alias bi='vi'
alias bonzo='echo "Bonzo on $(based-connect -b 28:11:A5:35:B8:18)%"'
alias cat='bat'
alias ccat='/usr/sbin/cat'
alias diff='diff -urN'
alias dos2unix='dos2unix -A'
alias git='LANG=en_US.UTF-8 git'
alias gource="gource --user-image-dir $HOME/.avatar"
alias grep='grep --color=auto -i'
alias iotop='sudo iotop -o -P'
alias la='ls -a'
alias lh='ls -d .??*'
alias ll='ls -l'
alias ls='ls --color=auto --group-directories-first'
alias octave='clear; octave --no-gui --quiet'
alias pkill='pkill -ec'
alias ps='ps ux'
alias pgcli-q1='pgcli postgres://postgres:docker@qpro-q1/misuse_pg'
alias pgcli-har='pgcli postgres://admin:admin@poweredge:5433/harmonia'
alias serial-out='screen /dev/ttyUSB0 9600'
alias ssh-cloud-ar='gcloud beta compute ssh --zone "us-central1-a" "vm-qpro-ar-experience" --project "qpro-ar-experience"'
alias ssh-cloud-shell='gcloud cloud-shell ssh'
alias ssh-cloud-showroom='gcloud beta compute ssh --zone "us-east4-c" "vm-qpro-showroom-rfid-swarm00" --project "qpro-showroom-rfid"'
alias ssh-cloud-ts='gcloud beta compute ssh --zone "us-central1-a" "vm-troubleshoot-manager" --project "qpro-troubleshoot"'
alias toff='synclient TouchpadOff=1'
alias ton='synclient TouchpadOff=0'
alias tree='tree -A'
alias vi='vi -p'
alias dmesg='journalctl -k -f'
alias lsd='ls -d */'
alias ipdata='curl ipinfo.io'


PATH="/home/paulo/bin:/usr/local/sbin:/usr/sbin:/sbin:${PATH}"

OPENSCADPATH="$HOME/.local/share/OpenSCAD/libraries"

export VISUAL="vim"

export WORKON_HOME=$HOME/.virtualenvs
source /usr/bin/virtualenvwrapper.sh
source /usr/share/fzf/key-bindings.bash

#eval $(docker-machine env suse-docker)

_dotnet_bash_complete()
{
  local word=${COMP_WORDS[COMP_CWORD]}

  local completions
  completions="$(dotnet complete --position "${COMP_POINT}" "${COMP_LINE}" 2>/dev/null)"
  if [ $? -ne 0 ]; then
    completions=""
  fi

  COMPREPLY=( $(compgen -W "$completions" -- "$word") )
}

complete -f -F _dotnet_bash_complete dotnet

export DOCKER_HOST="tcp://qpro-q1:2375"



