#!/usr/bin/bash/env python
# -*- coding:utf-8 -*-
# dummy comment


import readline, rlcompleter, os, atexit
readline.parse_and_bind('tab:complete')
history_file = os.path.expanduser('~/.pyhist')
readline.read_history_file(history_file)
atexit.register(readline.write_history_file, history_file)


