set bg=dark
filetype on
set modeline
set tabstop=4 shiftwidth=2 expandtab
set wildmode=list:longest
set number
set laststatus=2
let g:airline_theme='solarized'
syntax on
" set autoindent
set hlsearch

" Lembra posicao do cursor
autocmd BufReadPost *
	\ if line("'\"") > 1 && line("'\"") <= line("$") |
	\   exe "normal! g`\"" |
	\ endif


" {{{ Terminal fixes
if &term ==? "xterm"
	set t_Sb=^[4%dm
	set t_Sf=^[3%dm
	set ttymouse=xterm2
endif

au BufNewFile,BufRead *.pde setf cpp
au BufNewFile,BufRead *.prc setf sql
au BufNewFile,BufRead *.scl setf pascal


" mapeamento
"map <S-Left> :tabprevious<CR>
"map <S-Right> :tabnext<CR>
map <F1> :%!astyle -A3<CR>
map <C-Tab> gt
map <C-S-Tab> gT

